### PR TITLE
Drop support for ruby < 2.0.0. Update badges for voxpupuli

### PR DESCRIPTION
**Pull request by alexjfisher**
Also remove ruby 1.8 dev support.

### CODE REVIEW

**Comment by bastelfreak** [comment]
why do we even test on those legacy ruby version? Can't we just drop them?

**Comment by alexjfisher** [comment]
@bastelfreak Maybe.  I thought matching puppet-lint's testing matrix would be an ok starting point.  There can't be many OSes where ruby < 2.  And when developing, there's really no reason you couldn't just install rvm.

**Comment by alexjfisher** [comment]
I guess I'd also like to understand why the pinning of tins doesn't work on travis.  It works for me locally.

**Comment by alexjfisher** [comment]
I'm not actually sure it makes sense trying to specify different dependencies depending on the version of ruby.  So I've dropped everything < 2.0.

**Pull request merged**
